import {hash,inventory,matches,documentUrl,chunkMatches,treePosition,documentStatus,counted} from './forest-model.js';
const $=id=>document.getElementById(id),canvas=$('forest'),ctx=canvas.getContext('2d');
const api='/lite-api',demo=document.body.dataset.demo==='true'||new URLSearchParams(location.search).get('demo')==='1';
let catalog={datasets:[],documents:[]},selected=null,query='',dataset='',limit=40,chunks=null,picks=[],frame=0,loadToken=0,selectionToken=0,searchToken=0;
const labels={INDEXED:'В индексе',PENDING:'Ожидает обработки',ERROR:'Нужна проверка',MISSING:'Файл не найден',SKIPPED:'Пропущен'};
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n}
function say(message){$('status').textContent=message}
function clearSelection(){++selectionToken;selected=null;$('detail').hidden=true;$('detail').replaceChildren()}
async function request(path,options={}){const response=await fetch(api+path,{...options,signal:AbortSignal.timeout(30000)});if(!response.ok){const e=new Error('request');e.status=response.status;throw e}return response.json()}
function problem(error){return error.status===401||error.status===403?'Войдите в ЛЕС, чтобы открыть свои документы.':error.status===404?'Этот экран не подключён к каталогу ЛЕС. Откройте его из приложения.':'Не удалось получить данные. Проверьте состояние ЛЕС и повторите загрузку.'}
function filtered(){return catalog.documents.filter(d=>matches(d,chunks?'':query,dataset)&&(!chunks||chunks.some(c=>chunkMatches(d,c))))}
function drawSoon(){if(!frame)frame=requestAnimationFrame(()=>{frame=0;draw()})}
function render(){const docs=filtered();$('documents').replaceChildren();for(const d of docs.slice(0,limit)){const b=el('button',undefined,'doc');b.type='button';b.setAttribute('aria-pressed',String(selected?.id===d.id));const icon=el('span','▲','tree-icon');icon.setAttribute('aria-hidden','true');const text=el('span',String(d.label||'Без названия'),'name');text.append(el('small',`${d.chunks||0} фрагм. · ${documentStatus(d)}`));b.append(icon,text);b.onclick=()=>select(d);$('documents').append(b)}$('more').hidden=docs.length<=limit;$('count').textContent=`${counted(catalog.datasets.length,'роща','рощи','рощ')} · ${counted(catalog.documents.length,'документ','документа','документов')}`+(catalog.documents.length>900?' · на карте до 900':'');drawSoon()}
async function select(doc){const token=++selectionToken;selected=doc;const panel=$('detail');panel.hidden=false;panel.replaceChildren(el('h2',doc.label),el('p',`${doc.dataset||'Датасет'} · ${counted(doc.chunks||0,'фрагмент','фрагмента','фрагментов')}`),el('p',documentStatus(doc)));for(const c of (chunks||[]).filter(c=>chunkMatches(doc,c))){panel.append(el('blockquote',c.content));if(c.rrf_rank)panel.append(el('p',`Место в объединённой выдаче RRF: ${c.rrf_rank}`))}render();if(demo){panel.append(el('p','Демонстрационный документ. Здесь нет пользовательских файлов.'));return}if(doc.document_id){const a=el('a','Открыть источник ↗');a.href=documentUrl({id:doc.document_id,dataset_id:doc.dataset_id,file_name:doc.label});a.target='_blank';a.rel='noopener';panel.append(a);return}const note=el('p','Находим оригинал…');panel.append(note);try{const data=await request('/rag/documents?'+new URLSearchParams({dataset_id:doc.dataset_id,q:doc.label,limit:'100'}));if(token!==selectionToken)return;const exact=(data.documents||[]).filter(d=>d.dataset_id===doc.dataset_id&&d.file_name===doc.label);note.remove();if(exact.length===1&&documentUrl(exact[0])){const a=el('a','Открыть источник ↗');a.href=documentUrl(exact[0]);a.target='_blank';a.rel='noopener';panel.append(a)}else panel.append(el('p','Путь к оригиналу не найден однозначно. Проверьте файл в датасете.'))}catch(e){if(token===selectionToken)note.textContent=problem(e)}}
async function load(){const token=++loadToken;++selectionToken;++searchToken;$('reload').disabled=true;say('Загружаем каталог документов…');try{let data;if(demo){data={nodes:[]};for(const [i,name] of ['Проект дома','Исследования','Личная библиотека'].entries()){data.nodes.push({id:'ds:demo'+i,kind:'dataset',label:name});for(let n=0;n<24+i*12;n++)data.nodes.push({id:`demo${i}:${n}`,kind:'document',dataset_id:'demo'+i,dataset:name,label:`${['План','Заметки','Глава'][i]} ${n+1}.pdf`,chunks:5+(n*7)%120,status:'INDEXED'})}}else data=await request('/rag/graph/full');if(token!==loadToken)return;catalog=inventory(data);selected=null;chunks=null;$('detail').hidden=true;$('dataset').replaceChildren(new Option('Весь лес',''));for(const d of catalog.datasets)$('dataset').add(new Option(d.label,d.id.replace(/^ds:/,'')));if(!catalog.datasets.some(d=>d.id==='ds:'+dataset))dataset='';$('dataset').value=dataset;render();say(demo?'Демонстрация · вымышленные документы':catalog.documents.length?'Выберите документ или задайте вопрос.':'Лес пока пуст. Добавьте документы в датасет ЛЕС.')}catch(e){if(token===loadToken){say(problem(e));$('count').textContent=catalog.documents.length?'Показан предыдущий каталог':'Каталог недоступен'}}finally{if(token===loadToken)$('reload').disabled=false}}
$('reload').onclick=load;$('more').onclick=()=>{limit+=40;render()};$('dataset').onchange=()=>{clearSelection();dataset=$('dataset').value;chunks=null;++searchToken;limit=40;render();say(`Документов в выбранной области: ${filtered().length}`)};$('search').oninput=()=>{clearSelection();query=$('search').value;chunks=null;++searchToken;limit=40;render();say(`По названию найдено: ${filtered().length}`)};
$('search-form').onsubmit=async e=>{e.preventDefault();if(!query.trim())return;if(demo){say('В демонстрации доступен поиск по названию. Поиск по содержимому работает в ЛЕС.');return}const token=++searchToken;say('Ищем фрагменты в индексе…');try{const result=await request('/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,dataset_ids:dataset?[dataset]:undefined,top_k:20,max_chars:1600})});if(token!==searchToken)return;chunks=result.chunks||[];limit=40;render();const linked=chunks.filter(c=>catalog.documents.some(d=>chunkMatches(d,c))).length;say(`Найдено фрагментов: ${chunks.length}. Связано с деревьями: ${linked}.`);if(chunks.length&&!linked)say('Фрагменты найдены, но в ответе нет однозначной связи с каталогом. Откройте поиск в чате ЛЕС.')}catch(error){if(token===searchToken)say(problem(error))}};
function draw(){
  if(!ctx)return;const box=canvas.getBoundingClientRect(),w=box.width,h=box.height,dpr=Math.min(devicePixelRatio||1,2);if(!w||!h)return;
  canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);picks=[];
  const groups=catalog.datasets.filter(d=>!dataset||d.id==='ds:'+dataset),columns=Math.ceil(Math.sqrt(Math.min(groups.length,60)||1)),rows=Math.ceil(Math.min(groups.length,60)/columns);
  const top=w<650?200:245,areaH=Math.max(170,h-top-70),cellW=w/columns,cellH=areaH/Math.max(rows,1),visibleIds=new Set(filtered().map(d=>d.id));let budget=900;
  for(const [i,group] of groups.slice(0,60).entries()){
    const cx=cellW*(i%columns+.5),cy=top+cellH*(Math.floor(i/columns)+.5),rx=Math.min(cellW*.43,210),ry=Math.min(cellH*.4,100);
    ctx.save();ctx.shadowColor='#214b251c';ctx.shadowBlur=28;ctx.shadowOffsetY=16;ctx.fillStyle='#bbcfaa';ctx.beginPath();ctx.ellipse(cx,cy+8,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.restore();
    const ground=ctx.createRadialGradient(cx-rx*.3,cy-ry*.3,0,cx,cy,rx);ground.addColorStop(0,'#e1edc5');ground.addColorStop(1,'#aec692');ctx.fillStyle=ground;ctx.beginPath();ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2);ctx.fill();
    const docs=catalog.documents.filter(d=>'ds:'+d.dataset_id===group.id).sort((a,b)=>a.id.localeCompare(b.id));
    const take=Math.min(docs.length,budget,Math.max(8,Math.floor(900/Math.max(groups.length,1))));budget-=take;
    const trees=docs.slice(0,take).map((d,j)=>({d,...treePosition(d,j,take)})).sort((a,b)=>a.z-b.z);
    for(const t of trees){
      const x=cx+t.x*rx*.87,y=cy+t.z*ry*.8,scale=Math.min(1,Math.max(.3,rx/130))*Math.min(1,8/Math.sqrt(take||1)),height=t.height*scale,active=visibleIds.has(t.d.id),chosen=selected?.id===t.d.id;
      ctx.globalAlpha=active?1:.18;ctx.fillStyle='#254d2925';ctx.beginPath();ctx.ellipse(x+6*scale,y+3*scale,10*scale,3*scale,-.25,0,Math.PI*2);ctx.fill();
      if(chosen){ctx.strokeStyle='#174d31';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y+2,13*scale+4,5*scale+3,0,0,Math.PI*2);ctx.stroke()}
      ctx.fillStyle='#70654c';ctx.fillRect(x-1.5*scale,y-height*.5,3*scale,height*.55);const green=hash(t.d.id)%28;
      for(let tier=0;tier<3;tier++){const yy=y-height*.24-tier*height*.24,wide=(12-tier*2.8)*scale;ctx.fillStyle=`hsl(${139+green/3} ${30+green/2}% ${26+green/3+tier*4}%)`;ctx.beginPath();ctx.moveTo(x,yy-height*.56);ctx.quadraticCurveTo(x+wide*.7,yy-height*.12,x+wide,yy);ctx.quadraticCurveTo(x,yy+5*scale,x-wide,yy);ctx.quadraticCurveTo(x-wide*.6,yy-height*.2,x,yy-height*.56);ctx.fill();ctx.fillStyle='#e2f0ae24';ctx.beginPath();ctx.moveTo(x,yy-height*.56);ctx.lineTo(x,yy+2*scale);ctx.lineTo(x-wide,yy);ctx.closePath();ctx.fill()}
      ctx.globalAlpha=1;if(active)picks.push({doc:t.d,x,y:y-height*.45,r:Math.max(12,height*.6)});
    }
    ctx.fillStyle='#36533a';ctx.font='600 12px "Segoe UI",sans-serif';ctx.textAlign='center';const name=String(group.label);ctx.fillText(name.length>28?name.slice(0,27)+'…':name,cx,cy+ry+24,cellW-12);
  }
  if(groups.length>60){ctx.textAlign='center';ctx.fillText('Выберите датасет, чтобы рассмотреть его рощу',w/2,h-70)}
}
function pick(event){const rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top;return [...picks].reverse().find(p=>Math.hypot(p.x-x,p.y-y)<p.r)}
canvas.onclick=e=>{const hit=pick(e);if(hit)select(hit.doc)};canvas.onpointermove=e=>{canvas.style.cursor=pick(e)?'pointer':'default'};new ResizeObserver(drawSoon).observe(canvas);load();
