"""Controlled TF-vs-BM25 ablation on a frozen export; never writes the live index.

Input vectors must be generated by the same explicitly assigned embedding model.
Cases with no gold evidence are reported separately, not counted as correct recall.
"""
from __future__ import annotations

import argparse
from dataclasses import asdict
import hashlib
import json
from pathlib import Path
import statistics
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from qdrant_client import QdrantClient, models
from backend.light_qdrant_runtime import LightQdrantRuntime
from backend.inference.bm25_sparse import encode_bm25
from backend.inference.bm25_weighted import BM25Profile
from backend.retrieval_candidate import RetrievalCandidate, sparse_vector
from proxy.services.context_governor_service import conservative_token_estimate


def recall(hits, case, k):
    groups = case.get('gold_groups') or []
    if not groups:
        return None
    normalize = lambda text: ' '.join(str(text).casefold().replace('ё', 'е').split())
    found = 0
    for group in groups:
        ids = {str(item['point_id']) for item in group['support']}
        anchor = normalize(group.get('anchor') or '')
        found += any(hit.point_id in ids or (anchor and anchor in normalize(hit.text)) for hit in hits[:k])
    return found / len(groups)


def evaluate(snapshot, queries, cases, out: Path, executable: Path):
    if not snapshot.get('embedding_fingerprint') or snapshot['embedding_fingerprint'] != queries.get('embedding_fingerprint'):
        raise ValueError('Snapshot and query embedding contracts differ')
    points = [models.PointStruct(**point) for point in snapshot['points']]
    if not points or any(p.payload.get('embedding_fingerprint') != snapshot['embedding_fingerprint'] for p in points):
        raise ValueError('Snapshot mixes embedding contracts')
    dimensions = {len(p.vector['dense']) for p in points}
    if len(dimensions) != 1:
        raise ValueError('Snapshot mixes dense dimensions')
    dimension = dimensions.pop()
    by_query = {item['id']: item for item in queries['queries']}
    if len(by_query) != len(queries['queries']) or len({c['id'] for c in cases}) != len(cases):
        raise ValueError('Duplicate control-case identity')
    for case in cases:
        item = by_query[case['id']]
        if item['question'] != case['question'] or len(item['dense']) != dimension or not item.get('dataset_ids'):
            raise ValueError('Query text, dimensions or scope do not match the control case')
    # Only a fresh output directory may own this trial's native process and index.
    out.mkdir(parents=True, exist_ok=False)
    profile = BM25Profile.from_documents([p.payload['text'] for p in points])
    for p in points:
        p.vector = {'dense':p.vector['dense'], 'sparse_tf':sparse_vector(encode_bm25(p.payload['text'])),
                    'bm25_sparse':sparse_vector(profile.document(p.payload['text']))}
    runtime = LightQdrantRuntime(executable, out)
    client = None
    report = {'schema':'les.retrieval-trial.v1', 'profile':asdict(profile),
              'points':len(points), 'cases':len(cases), 'query_embedding_ms':queries.get('elapsed_ms'),
              'comparison':'same dense vectors, corpus, scope, native RRF and no reranker; sparse weights only',
              'context_token_counter':'conservative estimate, not the generation model tokenizer', 'runs':[]}
    try:
        runtime.start()
        client = QdrantClient(url=runtime.url, api_key=runtime.api_key, timeout=30, check_compatibility=False)
        collection = 'les_trial_bm25'
        client.create_collection(collection, vectors_config={'dense':models.VectorParams(size=dimension,distance=models.Distance.COSINE)},
            sparse_vectors_config={name:models.SparseVectorParams(modifier=models.Modifier.IDF) for name in ('bm25_sparse','sparse_tf')})
        for start in range(0,len(points),64):
            client.upsert(collection, points=points[start:start+64], wait=True)
        candidate = RetrievalCandidate(client,collection,profile)
        for index, case in enumerate(cases):
            query = by_query[case['id']]
            # Alternate order to avoid systematically favouring the warm second run.
            for weighted in ([False, True] if index % 2 == 0 else [True, False]):
                started = time.perf_counter()
                hits = candidate.search(query['question'],query['dense'],query['dataset_ids'],weighted=weighted)
                search_ms = (time.perf_counter()-started)*1000
                started = time.perf_counter()
                packed = candidate.context(hits[:8], max_tokens=6000,count_tokens=conservative_token_estimate)
                context_ms = (time.perf_counter()-started)*1000
                row = {'id':case['id'], 'weighted':weighted, 'recall5':recall(hits,case,5),
                       'recall10':recall(hits,case,10), 'search_ms':round(search_ms,2),
                       'context_ms':round(context_ms,2), 'hit_ids':[h.point_id for h in hits],
                       'context_tokens':packed['tokens'], 'context_budget':packed['budget'],
                       'sections':len(packed['evidence']['sections']),
                       'complete_sections':sum(s['complete'] for s in packed['evidence']['sections']),
                       'citations':len(packed['source_map']), 'omitted_hits':packed['omitted_hits']}
                report['runs'].append(row)
                (out/f"{case['id']}-{'bm25' if weighted else 'tf'}-evidence.json").write_text(
                    json.dumps(packed,ensure_ascii=False,indent=2),encoding='utf-8')
            print(f"case {index+1}/{len(cases)}", flush=True)
        report['summary'] = {}
        for mode in [False,True]:
            rows = [r for r in report['runs'] if r['weighted']==mode]
            scored = [r for r in rows if r['recall5'] is not None]
            report['summary']['bm25' if mode else 'tf'] = {
                'scored_cases':len(scored),'unanswerable_cases':len(rows)-len(scored),
                'recall5':statistics.mean(r['recall5'] for r in scored) if scored else None,
                'recall10':statistics.mean(r['recall10'] for r in scored) if scored else None,
                'search_median_ms':statistics.median(r['search_ms'] for r in rows),
                'context_median_ms':statistics.median(r['context_ms'] for r in rows)}
        (out/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
        (out/'manifest.json').write_text(json.dumps({'profile':asdict(profile),
            'embedding_fingerprint':snapshot['embedding_fingerprint'],
            'snapshot_sha256':hashlib.sha256(json.dumps(snapshot,sort_keys=True).encode()).hexdigest()},indent=2))
        return report
    finally:
        if client is not None:
            client.close()
        runtime.stop()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ('snapshot','queries','cases','output','qdrant-exe'):
        parser.add_argument('--'+name, required=True, type=Path)
    args = parser.parse_args()
    read = lambda path: json.loads(path.read_text(encoding='utf-8'))
    report = evaluate(read(args.snapshot),read(args.queries),read(args.cases),args.output,args.qdrant_exe)
    print(json.dumps(report['summary'],ensure_ascii=False,indent=2))


if __name__ == '__main__':
    main()
